# ZeroMQ socket on which to listen to. Either absolute path or relative to
# work-dir/network.
bind-socket: ipc://hw.sock

# Server mode. Can be either online or offline. In offline mode, the SPV
# daemon does not start and only the local wallet is available to query.
server-mode: online

# False positive rate for the bloom filters.
bloom-false-positive: 0.00001

# Database connection information.
database:
    testnet:
        sqlite:
            database: hw-wallet.sqlite3
            poolsize: 1
        mysql:
            database: haskoin_wallet_testnet
            poolsize: 1
            user:     root
            password: ""
            host:     localhost
            port:     5432
    prodnet:
        sqlite:
            database: hw-wallet.sqlite3
            poolsize: 1
        mysql:
            database: haskoin_wallet
            poolsize: 1
            user:     root
            password: ""
            host:     localhost
            port:     5432

# List of trusted bitcoin full-nodes to connect to.
bitcoin-full-nodes:
    testnet:
        - host: testnet-seed.alexykot.me
          port: 18333
        - host: testnet-seed.bitcoin.petertodd.org
          port: 18333
        - host: testnet-seed.bluematt.me
          port: 18333
        - host: testnet-seed.bitcoin.schildbach.de
          port: 18333
    prodnet:
        - host: seed.bitcoin.sipa.be
          port: 8333
        - host: dnsseed.bluematt.me
          port: 8333
        - host: dnsseed.bitcoin.dashjr.org
          port: 8333
        - host: seed.bitcoinstats.com
          port: 8333
        - host: bitseed.xf2.org
          port: 8333
        - host: seed.bitcoin.jonasschnelli.ch
          port: 8333


# Log file name. Either absolute path or relative to work-dir/network
log-file: hw.log

# PID file name. Either absolute path or relative to work-dir/network.
pid-file: hw.pid

# Compile time configuration value. Either absolute path or relative to
# work-dir. Can only be set as environment variable.
config-file: config.yml

# Default keyring name
keyring-name: main

# Default output size for commands such as page sizes.
output-size: 10

# Type of addresses to display. Example: external, internal
address-type: external

# Use reverse paging for diplaying addresses and txs when set to True.
reverse-paging: false

# Sign new and imported transactions.
sign-transactions: true

# Default fee to pay (in satoshi) for every 1000 bytes.
transaction-fee: 10000

# Minimum number of confirmations for spending coins and displaying balances.
minimum-confirmations: 0

# Display the balance including offline transactions
offline: false

# How command-line output should be displayed. Supported values are:
# normal, json or yaml.
display-format: normal

# Detach the SPV server from the terminal when launched
detach-server: false

# ZeroMQ socket to communicate with the server.
# Either absolute path or relative to the server work-dir/network path.
connect-uri: ipc://hw.sock

# Use Testnet3
use-testnet: false

# Haskoin working directory. Either absolute path or relative to userâ€™s home.
# Defaults to an appropriate OS-specific value.
work-dir: ""

# Log level. Valid values are debug, info, warn and error.
log-level: info

# Print verbose
verbose: false

